import React, { createContext, useContext, useState, useEffect } from 'react';

const ThemeLanguageContext = createContext();

export const translations = {
  EN: {
    pokemons: 'Pokémons',
    items: 'Items',
    favorites: 'Favorites',
    compare: 'Compare',
    pokemonSearch: 'Pokémon Search',
    searchPokemon: 'Enter a Pokémon name...',
    searchItem: 'Enter an item...',
    searchButton: 'Search',
    randomButton: 'Random',
    loadingList: 'Loading Pokémon list…',
    loadingItem: 'Loading item details…',
    loadingData: 'Loading Pokémon data…',
    errorPrefix: 'Error:',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    weight: 'Weight',
    height: 'Height',
    effectiveTypes: 'Effective types against',
    switchShiny: 'Switch to shiny',
    switchNormal: 'Switch to normal',
    addFavorite: 'Add to favorites',
    removeFavorite: 'Remove from favorites',
    moves: 'Moves',
    movesShow: 'Show Moves',
    movesHide: 'Hide Moves',
    moveName: 'Move',
    moveType: 'Type',
    movePower: 'Power',
    moveAccuracy: 'Accuracy',
    movePP: 'PP',
    moveLearnMethod: 'Learn Method',
    moveLevel: 'Level',
    noMoves: 'No moves found.',
    loadingMoves: 'Loading moves…',
    favoritesTitle: 'My Favorites',
    favoritesEmpty: 'No favorites yet. Search for a Pokémon and click ❤️ to save it!',
    compareTitle: 'Compare Pokémon',
    comparePokemon1: 'Pokémon 1',
    comparePokemon2: 'Pokémon 2',
    compareEmpty: 'Search a Pokémon above to compare',
    stats: {
      'hp': 'HP',
      'attack': 'Attack',
      'defense': 'Defense',
      'special-attack': 'Special Attack',
      'special-defense': 'Special Defense',
      'speed': 'Speed',
    },
  },
  CZ: {
    pokemons: 'Pokémoni',
    items: 'Předměty',
    favorites: 'Oblíbení',
    compare: 'Porovnat',
    pokemonSearch: 'Hledání Pokémonů',
    searchPokemon: 'Zadejte jméno Pokémona...',
    searchItem: 'Zadejte předmět...',
    searchButton: 'Hledat',
    randomButton: 'Náhodný',
    loadingList: 'Načítání seznamu Pokémonů…',
    loadingItem: 'Načítání detailů předmětu…',
    loadingData: 'Načítání dat Pokémona…',
    errorPrefix: 'Chyba:',
    settings: 'Nastavení',
    language: 'Jazyk',
    theme: 'Motiv',
    light: 'Světlý',
    dark: 'Tmavý',
    system: 'Systém',
    weight: 'Váha',
    height: 'Výška',
    effectiveTypes: 'Účinné typy proti',
    switchShiny: 'Přepnout na lesklého',
    switchNormal: 'Přepnout na normálního',
    addFavorite: 'Přidat do oblíbených',
    removeFavorite: 'Odebrat z oblíbených',
    moves: 'Útoky',
    movesShow: 'Zobrazit útoky',
    movesHide: 'Skrýt útoky',
    moveName: 'Útok',
    moveType: 'Typ',
    movePower: 'Síla',
    moveAccuracy: 'Přesnost',
    movePP: 'PP',
    moveLearnMethod: 'Způsob naučení',
    moveLevel: 'Úroveň',
    noMoves: 'Žádné útoky nenalezeny.',
    loadingMoves: 'Načítání útoků…',
    favoritesTitle: 'Moji oblíbení',
    favoritesEmpty: 'Zatím žádní oblíbení. Najděte Pokémona a klikněte na ❤️!',
    compareTitle: 'Porovnat Pokémony',
    comparePokemon1: 'Pokémon 1',
    comparePokemon2: 'Pokémon 2',
    compareEmpty: 'Vyhledejte Pokémona výše pro porovnání',
    stats: {
      'hp': 'ŽB',
      'attack': 'Útok',
      'defense': 'Obrana',
      'special-attack': 'Spec. útok',
      'special-defense': 'Spec. obrana',
      'speed': 'Rychlost',
    },
  },
  ES: {
    pokemons: 'Pokémons',
    items: 'Objetos',
    favorites: 'Favoritos',
    compare: 'Comparar',
    pokemonSearch: 'Búsqueda de Pokémon',
    searchPokemon: 'Ingresa un nombre de Pokémon...',
    searchItem: 'Ingresa un objeto...',
    searchButton: 'Buscar',
    randomButton: 'Aleatorio',
    loadingList: 'Cargando lista de Pokémons…',
    loadingItem: 'Cargando detalles del objeto…',
    loadingData: 'Cargando datos del Pokémon…',
    errorPrefix: 'Error:',
    settings: 'Ajustes',
    language: 'Idioma',
    theme: 'Tema',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
    weight: 'Peso',
    height: 'Altura',
    effectiveTypes: 'Tipos efectivos contra',
    switchShiny: 'Cambiar a shiny',
    switchNormal: 'Cambiar a normal',
    addFavorite: 'Añadir a favoritos',
    removeFavorite: 'Quitar de favoritos',
    moves: 'Movimientos',
    movesShow: 'Ver movimientos',
    movesHide: 'Ocultar movimientos',
    moveName: 'Movimiento',
    moveType: 'Tipo',
    movePower: 'Poder',
    moveAccuracy: 'Precisión',
    movePP: 'PP',
    moveLearnMethod: 'Método',
    moveLevel: 'Nivel',
    noMoves: 'No se encontraron movimientos.',
    loadingMoves: 'Cargando movimientos…',
    favoritesTitle: 'Mis Favoritos',
    favoritesEmpty: '¡Sin favoritos aún. Busca un Pokémon y haz clic en ❤️!',
    compareTitle: 'Comparar Pokémon',
    comparePokemon1: 'Pokémon 1',
    comparePokemon2: 'Pokémon 2',
    compareEmpty: 'Busca un Pokémon arriba para comparar',
    stats: {
      'hp': 'PS',
      'attack': 'Ataque',
      'defense': 'Defensa',
      'special-attack': 'Ataque Esp.',
      'special-defense': 'Defensa Esp.',
      'speed': 'Velocidad',
    },
  },
  FR: {
    pokemons: 'Pokémons',
    items: 'Objets',
    favorites: 'Favoris',
    compare: 'Comparer',
    pokemonSearch: 'Recherche Pokémon',
    searchPokemon: 'Entrez un nom de Pokémon...',
    searchItem: 'Entrez un objet...',
    searchButton: 'Chercher',
    randomButton: 'Aléatoire',
    loadingList: 'Chargement de la liste…',
    loadingItem: "Chargement de l'objet…",
    loadingData: 'Chargement des données…',
    errorPrefix: 'Erreur :',
    settings: 'Paramètres',
    language: 'Langue',
    theme: 'Thème',
    light: 'Clair',
    dark: 'Sombre',
    system: 'Système',
    weight: 'Poids',
    height: 'Taille',
    effectiveTypes: 'Types efficaces contre',
    switchShiny: 'Passer en chromatique',
    switchNormal: 'Passer en normal',
    addFavorite: 'Ajouter aux favoris',
    removeFavorite: 'Retirer des favoris',
    moves: 'Attaques',
    movesShow: 'Voir les attaques',
    movesHide: 'Masquer les attaques',
    moveName: 'Attaque',
    moveType: 'Type',
    movePower: 'Puissance',
    moveAccuracy: 'Précision',
    movePP: 'PP',
    moveLearnMethod: 'Méthode',
    moveLevel: 'Niveau',
    noMoves: 'Aucune attaque trouvée.',
    loadingMoves: 'Chargement des attaques…',
    favoritesTitle: 'Mes Favoris',
    favoritesEmpty: 'Aucun favori. Cherchez un Pokémon et cliquez sur ❤️ !',
    compareTitle: 'Comparer des Pokémon',
    comparePokemon1: 'Pokémon 1',
    comparePokemon2: 'Pokémon 2',
    compareEmpty: 'Recherchez un Pokémon ci-dessus pour comparer',
    stats: {
      'hp': 'PV',
      'attack': 'Attaque',
      'defense': 'Défense',
      'special-attack': 'Atq. Spé.',
      'special-defense': 'Déf. Spé.',
      'speed': 'Vitesse',
    },
  },
  JA: {
    pokemons: 'ポケモン',
    items: 'どうぐ',
    favorites: 'お気に入り',
    compare: 'くらべる',
    pokemonSearch: 'ポケモンけんさく',
    searchPokemon: 'ポケモンのなまえをにゅうりょく...',
    searchItem: 'どうぐのなまえをにゅうりょく...',
    searchButton: 'けんさく',
    randomButton: 'ランダム',
    loadingList: 'リストをよみこみちゅう…',
    loadingItem: 'どうぐをよみこみちゅう…',
    loadingData: 'データをよみこみちゅう…',
    errorPrefix: 'エラー:',
    settings: 'せってい',
    language: 'げんご',
    theme: 'テーマ',
    light: 'ライト',
    dark: 'ダーク',
    system: 'システム',
    weight: 'おもさ',
    height: 'たかさ',
    effectiveTypes: 'こうかばつぐんのタイプ:',
    switchShiny: 'いろちがいにきりかえ',
    switchNormal: 'ノーマルにきりかえ',
    addFavorite: 'お気に入りについか',
    removeFavorite: 'お気に入りからさくじょ',
    moves: 'わざ',
    movesShow: 'わざをみる',
    movesHide: 'わざをかくす',
    moveName: 'わざ',
    moveType: 'タイプ',
    movePower: 'いりょく',
    moveAccuracy: 'めいちゅう',
    movePP: 'PP',
    moveLearnMethod: 'おぼえかた',
    moveLevel: 'レベル',
    noMoves: 'わざがみつかりませんでした。',
    loadingMoves: 'わざをよみこみちゅう…',
    favoritesTitle: 'お気に入り',
    favoritesEmpty: 'お気に入りはまだありません。ポケモンをさがして❤️をおしてね！',
    compareTitle: 'ポケモンをくらべる',
    comparePokemon1: 'ポケモン１',
    comparePokemon2: 'ポケモン２',
    compareEmpty: 'くらべるポケモンをけんさくしてね',
    stats: {
      'hp': 'HP',
      'attack': 'こうげき',
      'defense': 'ぼうぎょ',
      'special-attack': 'とくこう',
      'special-defense': 'とくぼう',
      'speed': 'すばやさ',
    },
  },
  ZH: {
    pokemons: '宝可梦',
    items: '道具',
    favorites: '收藏',
    compare: '对比',
    pokemonSearch: '宝可梦搜索',
    searchPokemon: '输入宝可梦名称...',
    searchItem: '输入道具名称...',
    searchButton: '搜索',
    randomButton: '随机',
    loadingList: '正在加载列表…',
    loadingItem: '正在加载道具…',
    loadingData: '正在加载数据…',
    errorPrefix: '错误：',
    settings: '设置',
    language: '语言',
    theme: '主题',
    light: '浅色',
    dark: '深色',
    system: '系统',
    weight: '重量',
    height: '身高',
    effectiveTypes: '克制类型：',
    switchShiny: '切换为异色',
    switchNormal: '切换为普通',
    addFavorite: '添加收藏',
    removeFavorite: '取消收藏',
    moves: '招式',
    movesShow: '查看招式',
    movesHide: '隐藏招式',
    moveName: '招式',
    moveType: '属性',
    movePower: '威力',
    moveAccuracy: '命中',
    movePP: 'PP',
    moveLearnMethod: '学习方式',
    moveLevel: '等级',
    noMoves: '未找到招式。',
    loadingMoves: '正在加载招式…',
    favoritesTitle: '我的收藏',
    favoritesEmpty: '暂无收藏。搜索宝可梦并点击❤️来保存！',
    compareTitle: '对比宝可梦',
    comparePokemon1: '宝可梦 1',
    comparePokemon2: '宝可梦 2',
    compareEmpty: '请在上方搜索宝可梦进行对比',
    stats: {
      'hp': 'HP',
      'attack': '攻击',
      'defense': '防御',
      'special-attack': '特攻',
      'special-defense': '特防',
      'speed': '速度',
    },
  },
};

export const ThemeLanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('lang') || 'EN');
  const [theme, setTheme] = useState(() => localStorage.getItem('theme') || 'system');

  const getAppliedTheme = (t) => {
    if (t === 'system') return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    return t;
  };

  useEffect(() => { localStorage.setItem('lang', language); }, [language]);

  useEffect(() => {
    localStorage.setItem('theme', theme);
    document.documentElement.setAttribute('data-theme', getAppliedTheme(theme));
  }, [theme]);

  useEffect(() => {
    if (theme !== 'system') return;
    const mq = window.matchMedia('(prefers-color-scheme: dark)');
    const handler = () => document.documentElement.setAttribute('data-theme', mq.matches ? 'dark' : 'light');
    mq.addEventListener('change', handler);
    return () => mq.removeEventListener('change', handler);
  }, [theme]);

  const t = translations[language];

  return (
    <ThemeLanguageContext.Provider value={{ language, setLanguage, theme, setTheme, t }}>
      {children}
    </ThemeLanguageContext.Provider>
  );
};

export const useThemeLang = () => useContext(ThemeLanguageContext);